export const dataExperience = [
  {
    company: 'PT Majoo Teknologi Indonesia',
    work: [
      {
        desciption: 'Majoo (User Dashboard)',
        note: ['Application about online cashier that is used to control sales, products, inventory, reporting, invoice, market, stock of goods and others.'],
        year: '2021-Present'
      }
    ],
  },
  {
    company: 'PT Nusantara Sukses Teknologi',
    work: [
      {
        desciption: 'Siswamedia (Freelance)',
        note: ['Developing and refactoring code web admin siswamedia.com in a feature Ujian (Nilai and Pantau), Materi Belajar.'],
        year: 'Jul 2021 - Sept 2021'
      }
    ],
  },
  {
    company: 'Twiscode Pte. Ltd',
    work: [
      {
        desciption: 'Belanjaparts.com(admin+website)',
        note: [
          'Belanjaparts Admin -> Web Admin for manage of a hardware, tools, raw materials, and maintenance equipment industrial materials.',
          'Belanjaparts -> Supply Company is a supplier of hardware, tools, raw materials, and maintenance equipment industrial materials.'
        ],
        year: '2019 - 2021'
      },
      {
        desciption: 'Transpacific',
        note: [
          'ERP site Transpacific.',
        ],
        year: '2019 - 2021'
      },
      {
        desciption: 'InSys Admin Frontend-web - Legoas',
        note: [
          'Admin website used to organize and record objects that will be verified to be auctioned goods.',
        ],
        year: '2020'
      }
    ],
  },
  {
    company: 'Final Project College',
    work: [
      {
        desciption: 'Game Simulasi Blowgun',
        note: [
          'Developing a game controller using a mobile phone that consists of a sensor gyroscope and sending Data generated by a gyroscope sensor in the mobile phone will be used to determine the position of aim on a computer screen and the voice input will be used to the trigger to shoot a dart.',
        ],
        year: '-'
      }
    ],
  },
  {
    company: 'Freelance as Game Programmer',
    work: [
      {
        desciption: '-',
        note: [
          'Developed a education game about BMR and food calories (Okt - Nov).',
          'Developed a education game about daily japanese (Okt - Mar).',
          'Developed a education game about c ++ programming language in platform games (Okt - Jan).',
        ],
        year: 'Okt 2017 - Mar 2017'
      }
    ],
  },
  {
    company: 'Tahoe Games',
    work: [
      {
        desciption: 'Core Game Programmer (intern)',
        note: [
          'Developed a casual racing game and build the core program of the game and integrate game components (assets and program).',
        ],
        year: 'Jan 2017 - Feb 2017'
      }
    ],
  },
]